server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgresuser
    password: postgrespw
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always



order:
  outbox:
    clean:
      cron:
        expression: 0 0 0 * * *
      interval:
        days: 7